version: "3"

services:
  frontend:
    build: ./frontend
    stdin_open: true
    volumes:
      - ./frontend/:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    stdin_open: true
    ports:
      - "3001:3001"

